# Generated by Django 5.0.2 on 2024-03-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeee',
            new_name='Student',
        ),
    ]
